2024-12-04 21:47:15,675 ERROR: Exception on / [GET] [in /Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: user_roles

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask_login/utils.py", line 284, in decorated_view
    elif not current_user.is_authenticated:
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/werkzeug/local.py", line 318, in __get__
    obj = instance._get_current_object()
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/werkzeug/local.py", line 526, in _get_current_object
    return get_name(local())
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask_login/utils.py", line 25, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask_login/utils.py", line 370, in _get_user
    current_app.login_manager._load_user()
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask_login/login_manager.py", line 364, in _load_user
    user = self._user_callback(user_id)
  File "/Users/justin/Downloads/4th_quarter_2024_flask-blackfridaylunch/app/models.py", line 41, in load_user
    return User.query.get(int(id))
  File "<string>", line 2, in get
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/sqlalchemy/util/deprecations.py", line 386, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 1127, in get
    return self._get_impl(ident, loading.load_on_pk_identity)
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 1136, in _get_impl
    return self.session._get_impl(
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3873, in _get_impl
    return db_load_fn(
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/sqlalchemy/orm/loading.py", line 705, in load_on_pk_identity
    return result.one()
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/sqlalchemy/engine/result.py", line 1810, in one
    return self._only_one_row(
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/sqlalchemy/engine/result.py", line 749, in _only_one_row
    row: Optional[_InterimRowType[Any]] = onerow(hard_close=True)
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/sqlalchemy/engine/result.py", line 1673, in _fetchone_impl
    return self._real_result._fetchone_impl(hard_close=hard_close)
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/sqlalchemy/engine/result.py", line 2259, in _fetchone_impl
    row = next(self.iterator, _NO_ROW)
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/sqlalchemy/orm/loading.py", line 223, in chunks
    rows = [proc(row) for row in fetch]
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/sqlalchemy/orm/loading.py", line 223, in <listcomp>
    rows = [proc(row) for row in fetch]
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/sqlalchemy/orm/loading.py", line 1145, in _instance
    _populate_full(
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/sqlalchemy/orm/loading.py", line 1353, in _populate_full
    populator(state, dict_, row)
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/sqlalchemy/orm/strategies.py", line 2071, in load_collection_from_subq
    collection = collections.get(tuple_getter(row), ())
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/sqlalchemy/orm/strategies.py", line 1804, in get
    self._load()
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/sqlalchemy/orm/strategies.py", line 1820, in _load
    rows = list(q.params(self.params))
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2813, in __iter__
    result = self._iter()
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2827, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2362, in execute
    return self._execute_internal(
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2247, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/sqlalchemy/orm/context.py", line 305, in orm_execute_statement
    result = conn.execute(
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: user_roles
[SQL: SELECT role.id AS role_id, role.name AS role_name, role.notes AS role_notes, role.icon AS role_icon, role.created_at AS role_created_at, role.created_by AS role_created_by, role.updated_at AS role_updated_at, role.updated_by AS role_updated_by, anon_1.user_id AS anon_1_user_id 
FROM (SELECT user.id AS user_id 
FROM user 
WHERE user.id = ?) AS anon_1 JOIN user_roles AS user_roles_1 ON anon_1.user_id = user_roles_1.user_id JOIN role ON role.id = user_roles_1.role_id]
[parameters: (1,)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
